### ISSUE TITLE
Release Cynthion 0.1.0

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/cynthion#25]
This is the tracking issue for the Cynthion 1.0.0 release.

```[tasklist]
### Tasks not yet associated with an Issue or Pull Request
- [x] decision: How are updates going to work for each of 1. Host software,  2. Gateware
- [x] Add support for using Moondancer on Cynthion's Host USB port rather than Aux
- [x] Publish rust crates to crates.io
- [x] Resolve outstanding weirdnesses with soc & advertiser
```

```[tasklist]
### Documentation
- [ ] https://github.com/greatscottgadgets/cynthion/issues/194
- [ ] decision: getting_started.rs needs minimum recommended Rust version
- [ ] #27
- [ ] #26
- [ ] https://github.com/greatscottgadgets/cynthion/issues/83
- [x] image: getting_started.rst needs one or more photos or diagrams demonstrating how to connect the Cynthion hardware
- [x] decision: getting_started.rs needs minimum recommended Python version
- [ ] https://github.com/greatscottgadgets/cynthion/pull/33
- [ ] https://github.com/greatscottgadgets/cynthion/issues/84
```

```[tasklist]
### Issues
- [ ] #9
- [ ] https://github.com/greatscottgadgets/cynthion/issues/69
- [ ] https://github.com/greatscottgadgets/cynthion/issues/53
- [ ] https://github.com/greatscottgadgets/cynthion/issues/52
- [ ] https://github.com/greatscottgadgets/cynthion/issues/51
- [ ] https://github.com/greatscottgadgets/cynthion/issues/50
- [ ] https://github.com/greatscottgadgets/cynthion/issues/70
- [ ] https://github.com/greatscottgadgets/cynthion/issues/78
- [ ] https://github.com/greatscottgadgets/cynthion/issues/60
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/cynthion/pull/33
- [ ] https://github.com/greatscottgadgets/cynthion/pull/76
- [ ] https://github.com/greatscottgadgets/cynthion/pull/74
- [ ] #23
- [ ] https://github.com/greatscottgadgets/cynthion/pull/31
- [ ] https://github.com/greatscottgadgets/cynthion/pull/29
- [ ] https://github.com/greatscottgadgets/cynthion/pull/30
- [ ] https://github.com/greatscottgadgets/cynthion/pull/104
- [ ] https://github.com/greatscottgadgets/cynthion/pull/110
```
