### ISSUE TITLE
Outstanding firmware bugs

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/cynthion#60]
Tracking issue for some bugs that crop up rarely enough they haven't been diagnosed yet.

```[tasklist]
### Tasks
- [x] Firmware sometimes crashes if Facedancer exits unexpectedly.
- [x] Facedancer endpoint `handle_data_requested` gets called twice on libusb1.bulkRead
- [x] Doing a control transfer immediately after a bulk transfer gives `moondancer::read_endpoint(0) has no packet buffered for endpoint`
- [x] Facedancer `self.send` on IN endpoint does strange things if `blocking != True`
- [x] Don't try hanging extra attributes off a Python `Enum`. They're singletons! 🙈
- [x] fix usb-proxy breaking after bug fixes
- [x] fix mass-storage breaking after bug fixes
- [x] fix ftdi-echo breaking after bug fixes
- [x] extend torture test to do > max_ep_size transactions
- [x] Add torture test to facedancer.git unit tests
- [x] extend torture test to do both high and full speed tests
- [ ] https://github.com/greatscottgadgets/cynthion/pull/61
- [ ] https://github.com/greatscottgadgets/facedancer/pull/88
- [ ] https://github.com/greatscottgadgets/luna-soc/pull/15
- [ ] https://github.com/greatscottgadgets/luna-soc/pull/12
```
